export const randCaptionArray = [
    "#JunkInTheTrunk",
    "Flavor of the month",
    "I woke up like dis",
    "Today is going to be a good day",
    "Friendzoned",
    "Dream Big",
    "That sure gives me the warm fuzzies",
    "It's called fashion, look it up",
    "They should make a movie out of this",
    "Thats what kids do these days",
    "Reflection of my life choices",
    "Stay out of my safe space",
    "Chivalry is dead",
    "Chivalry isn't dead",
    "I am full of excitement",
    "Just when I'm out they pull me back in",
    "On a scale of 1-10 I'm a 27",
    "Preaching to the choir",
    "#blessed",
    "Come at me bro",
    "King of the world",
    "This is what perfection looks like",
    "Let's get this parted started",
    "I should have kept my day job",
    "I've been to hell and back",
    "Girl's night out",
    "U up?",
    "Forever alone",
    "I'll sleep when I'm dead",
    "Not all heroes wear capes",
    "The opposite of winning",
    "Try it, you'll like it",
    "This could all be yours for the low price of $5.99",
    "But at what cost??",
    "Embracing destiny",
    "Squad Goals",
    "#yolo",
    "Treat yo self",
    "Viewer descretion advised",
    "Boy band material",
    "This was fun while it lasted",
    "The struggle is real",
    "Hard pass",
    "That's what she said",
    "Too cool for school",
    "NSFW",
    "Finger lickin good",
    "This is why I'm single",
    "No caption needed",
    "This photo speaks for itself",
    "Not all who wander are lost",
    "Partner in crime",
    "Felt cute, might delete later",
    "Low quality pic, high quality friends",
    "New year, new me",
    "Good Vibes Only",
    
  ]